# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('host_ip', models.CharField(max_length=50)),
                ('src_ip', models.CharField(max_length=50, null=True)),
                ('dstip', models.CharField(max_length=50, null=True)),
                ('trans_layer_type', models.CharField(max_length=10)),
                ('ttl', models.IntegerField(null=True)),
                ('len', models.IntegerField(null=True)),
                ('src_mac', models.CharField(max_length=50, null=True)),
                ('dst_mac', models.CharField(max_length=50, null=True)),
                ('pcap_id', models.IntegerField(default=0)),
            ],
        ),
    ]
