# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcapdisplay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='dstip',
            new_name='dst_ip',
        ),
    ]
