# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapdisplay', '0002_auto_20161006_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='data_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
