# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapdisplay', '0003_package_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
